/* Generated by build_bundle_contents.py — do not hand-edit.
   One row per product family, with a picture of the real
   thing. Regenerate after any change to the bundles. */
const CONTENTS = {
 "VI_The_Complete_Collection": [
  {
   "name": "Advice for the couple",
   "note": "",
   "icon": "advicecard",
   "files": 1
  },
  {
   "name": "First anniversary letter",
   "note": "",
   "icon": "anniversaryletter",
   "files": 1
  },
  {
   "name": "The Budget Planner",
   "note": "",
   "icon": "budgetplanner",
   "files": 1
  },
  {
   "name": "Day-of details",
   "note": "",
   "icon": "dayof",
   "files": 1
  },
  {
   "name": "Drink tags",
   "note": "",
   "icon": "drinktags",
   "files": 1
  },
  {
   "name": "Engagement announcements",
   "note": "6 designs",
   "icon": "engagement",
   "files": 6
  },
  {
   "name": "Envelope liner & etiquette",
   "note": "2 designs",
   "icon": "envelope",
   "files": 2
  },
  {
   "name": "Favour tags",
   "note": "3 designs \u00b7 A4 & US Letter",
   "icon": "favourtags",
   "files": 6
  },
  {
   "name": "Find your seat",
   "note": "2 designs",
   "icon": "findyourseat",
   "files": 2
  },
  {
   "name": "Getting Ready Timeline",
   "note": "",
   "icon": "gettingreadytimeline",
   "files": 1
  },
  {
   "name": "Guest address labels",
   "note": "",
   "icon": "guest",
   "files": 1
  },
  {
   "name": "Invitation Suite \u2014 one combined file",
   "note": "",
   "icon": "invitationsuite",
   "files": 1
  },
  {
   "name": "The Invitation Suite",
   "note": "5 designs",
   "icon": "invite",
   "files": 5
  },
  {
   "name": "Menus",
   "note": "3 designs",
   "icon": "menu",
   "files": 3
  },
  {
   "name": "Open When Letters",
   "note": "",
   "icon": "openwhenletters",
   "files": 1
  },
  {
   "name": "Paperless RSVP guide",
   "note": "",
   "icon": "paperlessrsvpguide",
   "files": 1
  },
  {
   "name": "Petal cones",
   "note": "",
   "icon": "petalcones",
   "files": 1
  },
  {
   "name": "Photo card",
   "note": "",
   "icon": "photocard",
   "files": 2
  },
  {
   "name": "Place cards",
   "note": "4 designs \u00b7 A4 & US Letter",
   "icon": "placecards",
   "files": 8
  },
  {
   "name": "Wet weather plan",
   "note": "",
   "icon": "planb",
   "files": 1
  },
  {
   "name": "Print shop guide",
   "note": "",
   "icon": "printshopguide",
   "files": 1
  },
  {
   "name": "Paperless RSVP cards",
   "note": "2 designs",
   "icon": "qr",
   "files": 2
  },
  {
   "name": "Reading cards",
   "note": "",
   "icon": "readingcard",
   "files": 1
  },
  {
   "name": "Registry card",
   "note": "",
   "icon": "registrycard",
   "files": 1
  },
  {
   "name": "Rehearsal dinner",
   "note": "2 designs",
   "icon": "rehearsaldinner",
   "files": 2
  },
  {
   "name": "Return",
   "note": "",
   "icon": "return",
   "files": 1
  },
  {
   "name": "Reserved seat cards",
   "note": "",
   "icon": "seatcards",
   "files": 2
  },
  {
   "name": "The seating plan",
   "note": "A4 & US Letter",
   "icon": "seatingplan",
   "files": 2
  },
  {
   "name": "Signage",
   "note": "7 designs",
   "icon": "sign",
   "files": 7
  },
  {
   "name": "Table numbers",
   "note": "6 designs",
   "icon": "tablenumber",
   "files": 12
  },
  {
   "name": "Thank you cards",
   "note": "",
   "icon": "thankyou",
   "files": 1
  },
  {
   "name": "Thank you \u2014 combined file",
   "note": "",
   "icon": "thankyoubundle",
   "files": 1
  },
  {
   "name": "Thank you tracker",
   "note": "A4 & US Letter",
   "icon": "thankyoutracker",
   "files": 2
  },
  {
   "name": "Toast & reading cards",
   "note": "",
   "icon": "toastcard",
   "files": 1
  },
  {
   "name": "Vendor sheets",
   "note": "6 designs",
   "icon": "vendorsheet",
   "files": 6
  },
  {
   "name": "Vow books",
   "note": "",
   "icon": "vowskeepsake",
   "files": 1
  },
  {
   "name": "The Wedding Planner",
   "note": "A4 & US Letter",
   "icon": "weddingcollection",
   "files": 2
  },
  {
   "name": "Wedding party thank you",
   "note": "",
   "icon": "weddingpartythankyou",
   "files": 1
  },
  {
   "name": "Welcome bag card",
   "note": "",
   "icon": "welcomebag",
   "files": 1
  }
 ],
 "III_The_Invitation": [
  {
   "name": "Envelope liner & etiquette",
   "note": "2 designs",
   "icon": "envelope",
   "files": 2
  },
  {
   "name": "Guest address labels",
   "note": "",
   "icon": "guest",
   "files": 1
  },
  {
   "name": "Invitation Suite \u2014 one combined file",
   "note": "",
   "icon": "invitationsuite",
   "files": 1
  },
  {
   "name": "The Invitation Suite",
   "note": "5 designs",
   "icon": "invite",
   "files": 5
  },
  {
   "name": "Paperless RSVP guide",
   "note": "",
   "icon": "paperlessrsvpguide",
   "files": 1
  },
  {
   "name": "Print shop guide",
   "note": "",
   "icon": "printshopguide",
   "files": 1
  },
  {
   "name": "Paperless RSVP cards",
   "note": "2 designs",
   "icon": "qr",
   "files": 2
  },
  {
   "name": "Registry card",
   "note": "",
   "icon": "registrycard",
   "files": 1
  },
  {
   "name": "Return",
   "note": "",
   "icon": "return",
   "files": 1
  }
 ],
 "II_The_Planning": [
  {
   "name": "The Budget Planner",
   "note": "",
   "icon": "budgetplanner",
   "files": 1
  },
  {
   "name": "Print shop guide",
   "note": "",
   "icon": "printshopguide",
   "files": 1
  },
  {
   "name": "Vendor sheets",
   "note": "6 designs",
   "icon": "vendorsheet",
   "files": 6
  },
  {
   "name": "The Wedding Planner",
   "note": "A4 & US Letter",
   "icon": "weddingcollection",
   "files": 2
  }
 ],
 "IV_The_Ceremony": [
  {
   "name": "The Invitation Suite",
   "note": "",
   "icon": "invite",
   "files": 1
  },
  {
   "name": "Petal cones",
   "note": "",
   "icon": "petalcones",
   "files": 1
  },
  {
   "name": "Print shop guide",
   "note": "",
   "icon": "printshopguide",
   "files": 1
  },
  {
   "name": "Rehearsal dinner",
   "note": "2 designs",
   "icon": "rehearsaldinner",
   "files": 2
  },
  {
   "name": "Reserved seat cards",
   "note": "",
   "icon": "seatcards",
   "files": 2
  },
  {
   "name": "Signage",
   "note": "4 designs",
   "icon": "sign",
   "files": 4
  },
  {
   "name": "Welcome bag card",
   "note": "",
   "icon": "welcomebag",
   "files": 1
  }
 ],
 "I_The_Announcement": [
  {
   "name": "Engagement announcements",
   "note": "6 designs",
   "icon": "engagement",
   "files": 6
  },
  {
   "name": "The Invitation Suite",
   "note": "",
   "icon": "invite",
   "files": 1
  },
  {
   "name": "Print shop guide",
   "note": "",
   "icon": "printshopguide",
   "files": 1
  }
 ],
 "Ia_Your_Wedding_Online": [
  {
   "name": "Paperless RSVP guide",
   "note": "",
   "icon": "paperlessrsvpguide",
   "files": 1
  },
  {
   "name": "Print shop guide",
   "note": "",
   "icon": "printshopguide",
   "files": 1
  },
  {
   "name": "Paperless RSVP cards",
   "note": "2 designs",
   "icon": "qr",
   "files": 2
  }
 ],
 "VI_With_Thanks": [
  {
   "name": "First anniversary letter",
   "note": "",
   "icon": "anniversaryletter",
   "files": 1
  },
  {
   "name": "Envelope liner & etiquette",
   "note": "",
   "icon": "envelope",
   "files": 1
  },
  {
   "name": "Getting Ready Timeline",
   "note": "",
   "icon": "gettingreadytimeline",
   "files": 1
  },
  {
   "name": "Open When Letters",
   "note": "",
   "icon": "openwhenletters",
   "files": 1
  },
  {
   "name": "Photo card",
   "note": "",
   "icon": "photocard",
   "files": 2
  },
  {
   "name": "Wet weather plan",
   "note": "",
   "icon": "planb",
   "files": 1
  },
  {
   "name": "Print shop guide",
   "note": "",
   "icon": "printshopguide",
   "files": 1
  },
  {
   "name": "Return",
   "note": "",
   "icon": "return",
   "files": 1
  },
  {
   "name": "Thank you cards",
   "note": "",
   "icon": "thankyou",
   "files": 1
  },
  {
   "name": "Thank you \u2014 combined file",
   "note": "",
   "icon": "thankyoubundle",
   "files": 1
  },
  {
   "name": "Thank you tracker",
   "note": "A4 & US Letter",
   "icon": "thankyoutracker",
   "files": 2
  },
  {
   "name": "Vow books",
   "note": "",
   "icon": "vowskeepsake",
   "files": 1
  },
  {
   "name": "Wedding party thank you",
   "note": "",
   "icon": "weddingpartythankyou",
   "files": 1
  }
 ],
 "V_The_Reception": [
  {
   "name": "Advice for the couple",
   "note": "",
   "icon": "advicecard",
   "files": 1
  },
  {
   "name": "Day-of details",
   "note": "",
   "icon": "dayof",
   "files": 1
  },
  {
   "name": "Drink tags",
   "note": "",
   "icon": "drinktags",
   "files": 1
  },
  {
   "name": "Favour tags",
   "note": "3 designs \u00b7 A4 & US Letter",
   "icon": "favourtags",
   "files": 6
  },
  {
   "name": "Find your seat",
   "note": "2 designs",
   "icon": "findyourseat",
   "files": 2
  },
  {
   "name": "Menus",
   "note": "3 designs",
   "icon": "menu",
   "files": 3
  },
  {
   "name": "Place cards",
   "note": "4 designs \u00b7 A4 & US Letter",
   "icon": "placecards",
   "files": 8
  },
  {
   "name": "Print shop guide",
   "note": "",
   "icon": "printshopguide",
   "files": 1
  },
  {
   "name": "Reading cards",
   "note": "",
   "icon": "readingcard",
   "files": 1
  },
  {
   "name": "The seating plan",
   "note": "A4 & US Letter",
   "icon": "seatingplan",
   "files": 2
  },
  {
   "name": "Signage",
   "note": "3 designs",
   "icon": "sign",
   "files": 3
  },
  {
   "name": "Table numbers",
   "note": "6 designs",
   "icon": "tablenumber",
   "files": 12
  },
  {
   "name": "Toast & reading cards",
   "note": "",
   "icon": "toastcard",
   "files": 1
  }
 ]
};
